SELECT DISTINCT MANUFACTURER.COMPANY
FROM MANUFACTURER
JOIN PRODUCT
ON MANUFACTURER.BILL_ID = PRODUCT.BILL_ID
JOIN CATEGORY
ON CATEGORY.WARE = PRODUCT.WARE
WHERE CATEGORY.CLASS = 'Food'
OR CATEGORY.CLASS = 'Fuel'
